const SECONDS_PER_DATUM = 30;
export const DATUM_PER_TIMESTAMP = 4;
export const TIMESTAMP_DURATION = SECONDS_PER_DATUM * DATUM_PER_TIMESTAMP;
export const FREQUENCY_BINS = 5;
export const NB_SPECTROGRAM = 2;

export const MARGIN = {
  TOP: 100,
  RIGHT: 200,
  BOTTOM: 50,
  LEFT: 70,
};
export const CANVAS_DIMENSION = {
  WIDTH: 1000,
  HEIGHT: 1200,
};
export const DIMENSION = {
  WIDTH: CANVAS_DIMENSION.WIDTH - MARGIN.LEFT - MARGIN.RIGHT,
  HEIGHT: CANVAS_DIMENSION.HEIGHT - MARGIN.BOTTOM - MARGIN.TOP,
};
export const SPECTROGRAM_CANVAS_HEIGTH =
  CANVAS_DIMENSION.HEIGHT / NB_SPECTROGRAM;
export const SPECTROGRAM_HEIGHT =
  SPECTROGRAM_CANVAS_HEIGTH - (MARGIN.BOTTOM + MARGIN.TOP) / NB_SPECTROGRAM;
