name: Backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: python -m pip install -r requirements.txt -r requirements-dev.txt
      - run: python -m PyInstaller --onefile app.py
      - uses: actions/upload-artifact@v2
        with:
          name: "server_${{ matrix.os }}"
          path: backend/dist

  release:
    if: github.ref == 'refs/heads/master'

    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: "server_${{ matrix.os }}"
          path: backend/dist
      - uses: docker/build-push-action@v1
        with:
          dockerfile: backend/Dockerfile
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com/polycortex/polydodo
          repository: backend
          tags: latest
